Feature/registration page
chillhaze/team-project-client pull request #13
Opened 2022-01-17 18:57 UTC by maksik2018

reqistration + login page (markup )

2022-01-17 19:21 UTC, maksik2018 commented
from main to dev

2022-01-17 22:25 UTC, chillhaze requested changes

2022-01-17 22:25 UTC, chillhaze commented on src/pages/Login/Login.jsx
> +
название компонента Login, а экспортируется из него Register, если код дублируется, добавь пожалуйста один компонент, который  можно переиспользовать.

2022-01-18 12:32 UTC, chillhaze requested changes

2022-01-18 12:32 UTC, chillhaze commented on src/redux/auth/auth-operations.js
> +  'auth/signUp',
на беке нет энд-поинта 'auth/signUp'

2022-01-18 12:34 UTC, chillhaze requested changes

2022-01-18 12:34 UTC, chillhaze commented on src/redux/auth/auth-operations.js
> +  'auth/signIn',
на беке нет энд-поинта 'auth/signIn' ==>'auth/login'

2022-01-18 12:51 UTC, maksik2018 commented
Привет чуть изменил разметку, редакс пока не трогал, ждал данные по беку, сейчас буду смотреть

2022-01-18 14:41 UTC, chillhaze approved these changes

2022-01-18 14:41 UTC, merged